=== sped-mobi/progress-monitoring/src/Gisd.Sped.Progress/Schema/XML/sped-config.xsd
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:attributeGroup name="student.attributes">
    <xs:attribute name="firstName" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          The first name of the student.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="lastName" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          The last name of the student.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="localID" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          The district-assigned identifying number.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="dob" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>
          The student's date of birth following the pattern 'yyyy-MM-dd'.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="gender" type="gender.type"  use="required">
      <xs:annotation>
        <xs:documentation>
          The gender assigned to the student at birth.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="grade" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          The the current grade of the student.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="campus" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          The assigned campus of the student.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="accommodationGroup.attributes">
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name of the accommodation group.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="accommodation.attributes">
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          The name of the accommodation.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="subject" type="subject.list" use="required">
      <xs:annotation>
        <xs:documentation>
          List of subjects designating the environments that the accommodation should occur.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="schoolyear.attributes">
    <xs:attribute name="identifier" type="schoolyear.type" use="required">
      <xs:annotation>
        <xs:documentation>
          The title of the school year, such as 1998–1999.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="course.attributes">
    <xs:attribute name="title" type="xs:string" />
    <xs:attribute name="gen" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>General Education Time</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="spec" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Special Education Time</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="pgdb" type="pgdb.type" use="optional">
      <xs:annotation>
        <xs:documentation>Progress/Grade Determined By</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="annualGoal.attributes">
    <xs:attribute name="code" type="xs:string"  />
    <xs:attribute name="focus" type="focus.type" />
  </xs:attributeGroup>

  <xs:attributeGroup name="objective.attributes">
    <xs:attribute name="code" type="xs:string"  />
  </xs:attributeGroup>

  <xs:simpleType name="subject.list">
    <xs:list itemType="subject.type" />
  </xs:simpleType>

  <xs:simpleType name="subject.type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ELA">
        <xs:annotation>
          <xs:documentation>English/Language Arts</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Rdg" />
      <xs:enumeration value="Math" />
      <xs:enumeration value="SC" />
      <xs:enumeration value="PE" />
      <xs:enumeration value="SS" />
      <xs:enumeration value="FA" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="gender.type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Male" />
      <xs:enumeration value="Female" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="pgdb.type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Gen" />
      <xs:enumeration value="Spec" />
      <xs:enumeration value="Joint" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="schoolyear.type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="2019–2020" />
      <xs:enumeration value="2020–2021" />
      <xs:enumeration value="2021–2022" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="focus.type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Fine Arts" />
      <xs:enumeration value="Health" />
      <xs:enumeration value="Math" />
      <xs:enumeration value="Physical Education" />
      <xs:enumeration value="Science" />
      <xs:enumeration value="Social Studies" />
      <xs:enumeration value="Vocational Skills" />
      <xs:enumeration value="Speech" />
      <xs:enumeration value="Social/Emotional" />
      <xs:enumeration value="Reading" />
      <xs:enumeration value="English/Language Arts" />
      <xs:enumeration value="Activities of Daily Living II" />
      <xs:enumeration value="Written Expression" />
    </xs:restriction>
  </xs:simpleType>



  <xs:element name="configuration" type="configuration" />
  <xs:complexType name="configuration">
    <xs:sequence>
      <xs:element ref="schoolyear" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


  <xs:element name="schoolyear" type="schoolyear" />
  <xs:complexType name="schoolyear">
    <xs:sequence>
      <xs:element ref="students" minOccurs="0" />
    </xs:sequence>
    <xs:attributeGroup ref="schoolyear.attributes" />
  </xs:complexType>


  <xs:element name="students" type="students" />
  <xs:complexType name="students">
    <xs:sequence>
      <xs:element ref="student" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


  <xs:element name="student" type="student" />
  <xs:complexType name="student">
    <xs:sequence>
      <xs:element ref="accommodations" minOccurs="0" />
      <xs:element ref="scheduleOfServices" minOccurs="0" />
      <xs:element ref="annualGoals" minOccurs="0" />
    </xs:sequence>
    <xs:attributeGroup ref="student.attributes" />
  </xs:complexType>

  <xs:element name="accommodations" type="accommodations" />
  <xs:complexType name="accommodations">
    <xs:sequence>
      <xs:element ref="accommodationGroup" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="accommodationGroup" type="accommodationGroup" />
  <xs:complexType name="accommodationGroup">
    <xs:sequence>
      <xs:element ref="accommodation" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attributeGroup ref="accommodationGroup.attributes" />
  </xs:complexType>

  <xs:element name="accommodation" type="accommodation" />
  <xs:complexType name="accommodation">
    <xs:attributeGroup ref="accommodation.attributes" />
  </xs:complexType>

  <xs:element name="scheduleOfServices" type="scheduleOfServices" />
  <xs:complexType name="scheduleOfServices">
    <xs:sequence>
      <xs:element ref="course" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


  <xs:element name="course" type="course" />
  <xs:complexType name="course">
    <xs:attributeGroup ref="course.attributes" />
  </xs:complexType>

  <xs:element name="annualGoals" type="annualGoals" />
  <xs:complexType name="annualGoals">
    <xs:sequence>
      <xs:element ref="annualGoal" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="annualGoal" type="annualGoal">
    <xs:annotation>
      <xs:documentation>A measurable annual goal.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="annualGoal">
    <xs:sequence>
      <xs:element name="timeframe" type="xs:string" />
      <xs:element name="conditions" type="xs:string" />
      <xs:element name="behavior" type="xs:string" />
      <xs:element name="criteria" type="xs:string" />
      <xs:element ref="objectives" minOccurs="0" />
    </xs:sequence>
    <xs:attributeGroup ref="annualGoal.attributes" />
  </xs:complexType>

  <xs:element name="objectives" type="objectives" />
  <xs:complexType name="objectives">
    <xs:sequence>
      <xs:element ref="objective" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="objective" type="objective" />
  <xs:complexType name="objective">
    <xs:sequence>
      <xs:element name="timeframe" type="xs:string" />
      <xs:element name="conditions" type="xs:string" />
      <xs:element name="behavior" type="xs:string" />
      <xs:element name="criteria" type="xs:string" />
    </xs:sequence>
    <xs:attributeGroup ref="objective.attributes" />
  </xs:complexType>

</xs:schema>

=== sped-mobi/progress-monitoring/src/Gisd.Sped.Progress/Schema/XML/sped-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./sped-config.xsd">
  <schoolyear identifier="2020–2021">
    <students>
      <student firstName="Taylen" lastName="Beacham" dob="2008-05-20" localID="734282" gender="Male" grade="7" campus="O'Banion Middle School">
        <accommodations>
          <accommodationGroup name="Adapt Classroom Instruction">
            <accommodation name="Alternate Curriculum" subject="ELA Rdg Math SC SS"/>
            <accommodation name="Extended wait time for responses" subject="ELA Rdg Math SC PE SS FA"/>
            <accommodation name="Grades based on Grading Rubric for Participation and Socialization in a General Education Setting" subject="PE FA"/>
            <accommodation name="Grades based on Grading Rubric for Academic and Participation in a Special Education Setting" subject="ELA Rdg Math SC SS"/>
            <accommodation name="Information presented orally" subject="ELA Rdg Math SC SS"/>
            <accommodation name="Optional virtual/online instruction delivery" subject="ELA Rdg Math SC PE SS FA"/>
            <accommodation name="Pictures paired with text" subject="ELA Rdg Math SC SS"/>
            <accommodation name="Repeated verbal directions" subject="ELA Rdg Math SC PE SS FA"/>
            <accommodation name="Three (3) options for answer choices" subject="ELA Rdg Math SC SS"/>
            <accommodation name="Visual and verbal reminders to stay on task" subject="ELA Rdg Math SC PE SS FA"/>
          </accommodationGroup>
          <accommodationGroup name="Adapted or Additional Materials">
            <accommodation name="Math Manipulatives: Counters (Unifix Cubes, Dice, Beads, etc.)" subject="Math"/>
            <accommodation name="Math Manipulatives: Measuring devices (rulers, tape measure, etc.)" subject="Math"/>
            <accommodation name="Math Manipulatives: Number chart/line" subject="Math"/>
            <accommodation name="Math Manipulatives: Real or Play Money" subject="Math"/>
          </accommodationGroup>
          <accommodationGroup name="Alter Assignments or Testing">
            <accommodation name="Exemption from final/semester tests" subject="ELA Rdg Math SC PE SS FA"/>
          </accommodationGroup>
          <accommodationGroup name="Manage Behavior">
            <accommodation name="Clearly defined/consistent limits" subject="ELA Rdg Math SC PE SS FA"/>
            <accommodation name="Follow behavior intervention plan" subject="ELA Rdg Math SC PE SS FA"/>
            <accommodation name="Positive reinforcement" subject="ELA Rdg Math SC PE SS FA"/>
            <accommodation name="Preferential seating" subject="ELA Rdg Math SC PE SS FA"/>
          </accommodationGroup>
          <accommodationGroup name="Supports for School Personnel">
            <accommodation name="Support for general education teacher (provided by Special Ed. Staff)" subject="PE FA"/>
          </accommodationGroup>
        </accommodations>
        <scheduleOfServices>
          <course title="Art (Recreation/Leisure II)" gen="1 period (A or B day)" pgdb="Gen"/>
          <course title="English/Language Arts/Reading (Communications II)" spec="1 period (A or B day)" pgdb="Spec"/>
          <course title="Health ( Personal Health &amp; Hygiene II)" spec="1 period (A or B day)" pgdb="Spec"/>
          <course title="Math (Applied Consumer Skills II)" spec="1 period (A or B day)" pgdb="Spec"/>
          <course title="Physical Education (Partners in PE II)" gen="1 period (A or B day)" pgdb="Gen"/>
          <course title="Science (Applied Environmental Awareness II)" spec="1 period (A or B day)" pgdb="Spec"/>
          <course title="Social Studies (Community Citizenship II)" spec="1 period (A or B day)" pgdb="Spec"/>
          <course title="Vocation (Applied Marketable Skills II)" spec="1 period (A or B day)" pgdb="Spec"/>
        </scheduleOfServices>
        <annualGoals>
          <!--<annualGoal code="1" focus="Speech">
            <timeframe>From ARD year to ARD year</timeframe>
            <conditions>when given a visual and/or verbal direct cue(s)</conditions>
            <behavior>Taylen will communicate with others to express his knowledge and make requests</behavior>
            <criteria>with 70% accuracy</criteria>
            <objectives>
              <objective code="1.1">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given a verbal an/or visual direct cue(s)</conditions>
                <behavior>Taylen will follow one-step directions to complete activities/tasks</behavior>
                <criteria>with 70% accuracy</criteria>
              </objective>
              <objective code="1.2">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given a verbal an/or visual direct cue(s)</conditions>
                <behavior>Taylen will use a phrase or sentence to answer wh-questions about a story/recent event using picture cues</behavior>
                <criteria>with 70% accuracy</criteria>
              </objective>
              <objective code="1.3">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given a verbal an/or visual direct cue(s)</conditions>
                <behavior>Taylen will request desired items using a phrase or sentence</behavior>
                <criteria>with 70% accuracy</criteria>
              </objective>
            </objectives>
          </annualGoal>-->
          <annualGoal code="2" focus="Health">
            <timeframe>From ARD year to ARD year</timeframe>
            <conditions>when given visual and verbal reminders to stay on task and with extended wait time for responses</conditions>
            <behavior>Taylen will recall ways to enhance and maintain personal health, and identify body structures and functions that relate to personal health</behavior>
            <criteria>70% of the time</criteria>
            <objectives>
              <objective code="2.1">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given a visual representation displaying a labeled food pyramid along with several pictures of labelled food items from each food category found on the pyramid</conditions>
                <behavior>Taylen will select with his voice a balanced meal from the labelled food item pictures</behavior>
                <criteria>70% of the time</criteria>
              </objective>
              <objective code="2.2">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given picture representations of the circulatory, muscular, skeletal, nervous, respiratory, and digestive body systems and a blank full human body poster</conditions>
                <behavior>Taylen will match each body system to its corresponding location on the poster</behavior>
                <criteria>70% of the time</criteria>
              </objective>
            </objectives>
          </annualGoal>
          <annualGoal code="3" focus="Physical Education">
            <timeframe>From ARD year to ARD year</timeframe>
            <conditions>when given appropriate wait time for responses and visual and verbal reminders to stay on task</conditions>
            <behavior>Taylen will safely engage to completion light-to-moderate physical activities</behavior>
            <criteria>70% of the time</criteria>
            <objectives>
              <objective code="3.1">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given repeated physical demonstrations of the planned activity by the PE Coach and/or staff/peer, repeated verbal step by step descriptions of the activities using simplified language by the PE coach and/or staff/peer</conditions>
                <behavior>Taylen will participate in light-to-moderate health-related physical activities on a by properly completing the demonstrated warm up and cool down procedures for the planned activity</behavior>
                <criteria>70% of the time</criteria>
              </objective>
              <objective code="3.2">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given repeated physical demonstrations of the planned activity by the PE Coach and/or staff/peer, repeated verbal step by step descriptions of the activities using simplified language by the PE coach and/or staff/peer, and frequent verbal feedback on his performance</conditions>
                <behavior>Taylen will participate in light -to-moderate health-related physical activities on a regular basis by properly completing the demonstrated planned activity</behavior>
                <criteria>70% of the time</criteria>
              </objective>
            </objectives>
          </annualGoal>
          <annualGoal code="4" focus="Fine Arts">
            <timeframe>From ARD year to ARD year</timeframe>
            <conditions>when given verbal and visual reminders to stay on task</conditions>
            <behavior>Taylen will demonstrate appreciation for Fine Arts through production of original artworks using a variety of media</behavior>
            <criteria>70% of the time</criteria>
            <objectives>
              <objective code="4.1">
                <timeframe>From ARD year to ARD year</timeframe>
                <conditions>when given a partially completed work of art to be used as a guide, a variety of materials, such as paint, paint brushes, colored pencils, markers, crayons, chalk, molding clay, stencils, and cut outs</conditions>
                <behavior>Taylen will demonstrate artistic competence by selecting the appropriate materials he must use and presenting these material choices to a teacher</behavior>
                <criteria>70% of the time</criteria>
